### PR TITLE
PHP 8.2 | Fix "Use of "parent" in callables is deprecated" notice

### PR DESCRIPTION
**Pull request by jeffreyvanhees**

### CODE REVIEW

**Comment by glorand** [comment]
Hey @jeffreyvanhees thanks for your contribution! Can you fix please the Scrutinizer error here, as is done I can approve and merge your contribution.

**Comment by jeffreyvanhees** [comment]
> Hey @jeffreyvanhees thanks for your contribution! Can you fix please the Scrutinizer error here, as is done I can approve and merge your contribution.

Hmm, I think it's a problem in Scrutinizer itself:

```
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/scrutinizer/.analysis/phpcs/vendor/squizlabs/php_codesniffer/src/Config.php on line 399
```

I'll take a look at it this weekend.

**Comment by glorand** [comment]
Merged

**Comment by jeffreyvanhees** [comment]
@glorand Can you tag a new version so we can update by composer?

**Pull request merged**
